version: '3.7'

# The different services that make up our "network" of containers
services:
    neo:
        image: neo4j:latest
        ports: 
            - 7474:7474
            - 7687:7687
        volumes:
            - neo4j_data:/data/
        env_file:
            - .env.neo4j
volumes:
    neo4j_data: {}